[package]
name = "trybuild"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3"
lazy_static = "1.3"
remain = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termcolor = "1.0"
toml = "0.5"
